### ISSUE TITLE
二维码功能异常

### ISSUE THREAD

**Issue by iwshw888** [Xhofe/alist-web#1]
扫码打开后直接404?

**Comment by Xhofe** [comment]
> 扫码打开后直接404?

请主要配置文件中的`info.site_url`需要正确填写哦，后面不能带`/`，如果还是有问题，麻烦提供一下地址，邮箱：“i@nn.ci”

**Comment by jing5460** [comment]
二维码正常，另外一个人问题，后面上传的文件为何显示不出来？只能重新build吗

**Comment by Xhofe** [comment]
> 二维码正常，另外一个问题，后面上传的文件为何显示不出来？只能重新build吗

请注意看文档中的介绍哈，为了提高响应速度，对文件的列表是有缓存的，默认开启，在配置文件中可以设置缓存时间或者关闭缓存，或者手动访问一个指定的地址刷新缓存，地址为:`后端地址/cache/配置文件中的刷新缓存密码`，如`https://alist.nn.ci/cache/password`。

**Comment by jing5460** [comment]
明白了.谢谢
