### ISSUE TITLE
2条关于前端的功能建议

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#13]
Xhofe您好！

最近看到Github对于README.md的阅读有优化，所以联想到这个项目的前端应该也可以仿照优化一下，以下两点

1. 将前端原本默认的 `Readme.md` 标题改为 `README.md` 。

![image](https://user-images.githubusercontent.com/53750381/112718531-9110d880-8f2e-11eb-8d05-ec20caf91060.png)

这一点因为后续我没有测试新版，所以不知道是否是**同步文件名**的还是**默认就是标题Readme.md**

我自己从一开始使用最原始的版本的时候是Readme.md，我就再后来每次都把标题改成大写的，这样感觉更加规范一些？

当然这个只是我的个人建议，如果不需要可以忽略。更改的话也很简单，只需要更改这一行 https://github.com/Xhofe/alist-web/blob/ddf4191f978997ac0bd556583dcb74b59e293933/src/components/Readme.vue#L18 的 `Readme` 为 `README` 好像就行了。

2. 前端Markdown文件目录，Github的新版README.md文件目录的显示方式我觉得很有意思，我不知道加一个这个是否方便，如下图：

![image](https://user-images.githubusercontent.com/53750381/112718615-27dd9500-8f2f-11eb-99e3-73cb78d19fa2.png)

这种有目录的确实方便了太多，不用手动加入 `[TOC]` （可能加入了`[TOC]`还不支持显示）。

以上两点仅仅是我个人的想法，再次感谢。

**Comment by Xhofe** [comment]
- readme判断现在是大小写模糊的：
https://github.com/Xhofe/alist-web/blob/ddf4191f978997ac0bd556583dcb74b59e293933/src/components/Readme.vue#L43
- markdown的展示是用的现成的组件，重写写一个还是挺麻烦的，而且我觉得这个需求应该不是很多。
