### ISSUE TITLE
json文件无法预览，内容显示[object]

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#14]
如题，今天刚刚发现的。

在前端中**有密码**文件夹内 json 文件无法预览。推测是 alist-web 这里的问题。

**Comment by Xhofe** [comment]
现在的版本已经没有使用kkfileview了。。

**Comment by MFYDev** [comment]
尴尬了，我才想起来最新版不用这个了……

目前遇到的问题是这样，应该是文件预览哪里出现了问题，我不知道您那里是否能够复现
