### ISSUE TITLE
阿里云盘防盗链问题

### ISSUE THREAD

**Issue by tonyscy** [Xhofe/alist-web#19]
部署完成之后，点击一个文件下载按钮，直接报错为xml页面
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>60A4A9709971273430D05D11</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>

下面为部分日志
[GIN] 2021/05/19 - 13:48:20 | 200 |      1.4202ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 13:48:21 | 200 |      1.0936ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 13:48:23 | 200 |    308.5531ms |       127.0.0.1 | POST     "/api/rebuild"
[GIN] 2021/05/19 - 13:48:23 | 200 |      2.0182ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 13:48:24 | 200 |      1.0021ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 13:48:41 | 200 |      1.4336ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 13:55:33 | 200 |       988.5µs |       127.0.0.1 | GET      "/root1/ISO镜像/Linux/Kali"
[GIN] 2021/05/19 - 13:55:34 | 200 |       459.2µs |       127.0.0.1 | GET      "/api/info"
[GIN] 2021/05/19 - 13:55:34 | 200 |      2.7001ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 14:00:14 | 200 |       1.258ms |       127.0.0.1 | POST     "/api/path"
[GIN] 2021/05/19 - 14:00:14 | 301 |    221.2836ms |       127.0.0.1 | GET      "/d/root1/ISO镜像/Linux/Kali/kali-linux-2021.1-installer-amd64.iso?pw=907325c69271ddf0"

**Comment by Xhofe** [comment]
token的问题。使用手机端token即可
