### ISSUE TITLE
最新pr合并之后无法渲染前端md

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#21]
您好，刚刚下载了最新合并的pr中构建的版本，然后发现无法渲染前端md文件了，但是文件依然可以正常下载。

@daofeng2015 同样也需要daofeng帮忙看一下，是否是哪里出错了呢？

前后端一起更新的最新build，同时rebuild过。

**Comment by daofeng2015** [comment]
> 您好，刚刚下载了最新合并的pr中构建的版本，然后发现无法渲染前端md文件了，但是文件依然可以正常下载。
> 
> @daofeng2015 同样也需要daofeng帮忙看一下，是否是哪里出错了呢？
> 
> 前后端一起更新的最新build，同时rebuild过。

前端也需要更新..我改了路径
