### ISSUE TITLE
[BUG] 重构目录时输入数均失效

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#22]
![image](https://user-images.githubusercontent.com/53750381/119963292-829c7700-bfda-11eb-9776-364bd6b31689.png)

![image](https://user-images.githubusercontent.com/53750381/119963303-85976780-bfda-11eb-95ed-6fd04b1472e2.png)

使用版本为最新的master branch尚未release的版本，发现重构时无论输入任何数字均失效，上午那会还是正常的，重启alist也无效，输入正数同样无效提示此错误。

**Comment by Xhofe** [comment]
修改配置文件中的ali_drive. max_files_count到200以下然后重启试试

**Comment by MFYDev** [comment]
成功了，感谢Xhofe！

万万没想到和这个有关。。。

**Comment by PdA1337** [comment]
> 修改配置文件中的ali_drive. max_files_count到200以下然后重启试试

那么如果总文件数量大于200，如何处理呢

**Comment by Xhofe** [comment]
> > 修改配置文件中的ali_drive. max_files_count到200以下然后重启试试
> 
> 那么如果总文件数量大于200，如何处理呢

会自动使用marker处理的 不会丢失文件。
