### ISSUE TITLE
音视频播放：推荐使用vue-plyr替代vue-aplayer

### ISSUE THREAD

**Issue by dingpengyu** [Xhofe/alist-web#3]
感谢作者开发了这个程序：
我是一名视障用户。
今天早上在腾讯云轻量部署完 alist-web测试音频播放器时，发现键盘无法正常与 vue-aplayer 的 音频控制工具栏进行交互。
主要是按钮没有title 名称，和 播放时间的滑动条
于是我去了 [vue-aplayer](https://github.com/SevenOutman/vue-aplayer) 的GitHub存储库进行了查看，发现vue-aplayer本来就没有 accessible 的支持。
基于以上情况，看看开发者有没有可能使用 vue-plyr代替 vue-aplayer
以下是 vue-plyr 的[github 地址](https://github.com/redxtech/vue-plyr)
这是 [plyr](https://github.com/sampotts/plyr)的官方存储库
谢谢

**Comment by Xhofe** [comment]
> 感谢作者开发了这个程序：
> 我是一名视障用户。
> 今天早上在腾讯云轻量部署完 alist-web测试音频播放器时，发现键盘无法正常与 vue-aplayer 的 音频控制工具栏进行交互。
> 主要是按钮没有title 名称，和 播放时间的滑动条
> 于是我去了 [vue-aplayer](https://github.com/SevenOutman/vue-aplayer) 的GitHub存储库进行了查看，发现vue-aplayer本来就没有 accessible 的支持。
> 基于以上情况，看看开发者有没有可能使用 vue-plyr代替 vue-aplayer
> 以下是 vue-plyr 的[github 地址](https://github.com/redxtech/vue-plyr)
> 这是 [plyr](https://github.com/sampotts/plyr)的官方存储库
> 谢谢

之前没有考虑过 accessible 的支持，plyr确实做的更好，我会尽快完成替换。

**Comment by dingpengyu** [comment]
感谢
刚刚看到了您提交的plyr的测试分知，我部署做了测试，播放器工作正常，但播放器的语言维英文，以下是截图：
![image](https://user-images.githubusercontent.com/26911141/105619257-9ae16700-5e2b-11eb-8672-3c0b7bc76722.png)

**Comment by dingpengyu** [comment]
[测试地址](http://demo.imydd.top:5244/5fb5fdce5f2d695e2d7b47838789adc1a7f30671)

**Comment by dingpengyu** [comment]
[测试地址](http://demo.imydd.top:5244/5fb5fdce5f2d695e2d7b47838789adc1a7f30671)

**Comment by Xhofe** [comment]
已经添加了plyr中文支持，手动翻译可能会有一些出入，欢迎反馈。因为plyr仅支持html5的音视频，没有dplayer支持的多，所以还不会将主分支替换为plyr，之后会在plyr分支中同步更新，可以在[GitHub Actions](https://github.com/Xhofe/alist-web/actions?query=workflow%3Abuild-plyr)下载最新版本的dist。

**Comment by dingpengyu** [comment]
> 已经添加了plyr中文支持，手动翻译可能会有一些出入，欢迎反馈。因为plyr仅支持html5的音视频，没有dplayer支持的多，所以还不会将主分支替换为plyr，之后会在plyr分支中同步更新，可以在[GitHub Actions](https://github.com/Xhofe/alist-web/actions?query=workflow%3Abuild-plyr)下载最新版本的dist。

感谢。

**Comment by jing5460** [comment]
mp3音频这一块可以 添加自动播放下一首歌曲功能吗

**Comment by Xhofe** [comment]
> mp3音频这一块可以 添加自动播放下一首歌曲功能吗

这个不太好实现 我会好好想一想。

**Comment by jing5460** [comment]
或者在播放列表中显示所有歌曲文件！

**Comment by jing5460** [comment]
或者播放的时候，播放器停留在当前页面，而不需要跳转，谢谢
