### ISSUE TITLE
1.0.0 不支持的数据库类型 无法启动

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#6]
刚更新到1.0.0， ubuntu 20.04 最新版无法运行，之前版本可以

**Comment by Xhofe** [comment]
> 刚更新到1.0.0， ubuntu 20.04 最新版无法运行，之前版本可以

不好意思啊，先release了，教程还在写

**Comment by MFYDev** [comment]
抱歉，不小心开错了第一个issue的位置。
非常感谢及时解答，已收到您的回复，这就关闭等待最新教程。
