### ISSUE TITLE
v1.0.0 release arm64版本 数据库初始化失败

### ISSUE THREAD

**Issue by YujiaCheng1996** [Xhofe/alist-web#7]
debian 10 arm64 报错信息：
INFO[2021-03-13 21:30:41] 初始化数据库...                                    

2021/03/13 21:30:41 /home/runner/work/alist/alist/bootstrap/model.go:23
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
ERRO[2021-03-13 21:30:41] 连接数据库出现错误:Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub 
ERRO[2021-03-13 21:30:41] 初始化数据库出现错误,启动失败.

**Comment by Xhofe** [comment]
额，没有发现GoReleaser不支持CGO，我去重新上传一下release。

**Comment by YujiaCheng1996** [comment]
发错项目了，坐等新release。

**Comment by Xhofe** [comment]
应该可以了 不行再说一下。
