### ISSUE TITLE
demo是怎样部署到pages上的

### ISSUE THREAD

**Issue by zws13579** [Xhofe/alist-web#74]
我也想部署到pages上，但是怎么弄都不行，能出个教程吗？谢谢。

**Comment by xhofe** [comment]
pages上只是前端，你还是需要一个后端程序。

**Comment by ghost** [comment]
> pages上只是前端，你还是需要一个后端程序。

所以有教程吗？我直接下载了Releases里的dist.zip，解压后直接上传了cloudflare pages，搭建出来是https://a-lisyt.pages.dev/ ，功能缺失
