### ISSUE TITLE
是否可以将前端默认文件排序更改为默认文件名从小到大形式？

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist-web#8]
尊敬的Xhofe你好！

已打赏~

由于我的网盘后续加入一些需要按照顺序阅读的文件，是否有考虑过将默认排序更改为文件名从小到大形式呢？默认的排序好像是从大到小，感觉有些反人类，如果可以不胜感激！

**Comment by Xhofe** [comment]
根据习惯 ，默认的排序是按照更新时间的～越新的文件越靠前

**Comment by MFYDev** [comment]
啊明白，那如果说自己更改的话，我对于java和go并不是特别熟悉，这里我自己改方便吗？如果方便可以麻烦您指出一下具体哪一行定义的吗？我可以自己改一下~

万分感谢了~

**Comment by Xhofe** [comment]
在这里给files添加一个排序：https://github.com/Xhofe/alist-web/blob/1804247297dd9cfbafd6eb6fb5988e27ce30e639/src/store/index.ts#L119
按照你的要求，简单来写大概是
```ts
...
         state.audios = audios
+        files.sort((a,b)=>{
+         return a.name>b.name?1:-1
+        })
...
```

**Comment by MFYDev** [comment]
收到！已成功部署！非常感谢Xhofe！
