### ISSUE TITLE
为什么前后端都下载了1.0.1还是现实需要更新呢

### ISSUE THREAD

**Issue by szsyzx** [Xhofe/alist-web#9]
INFO[2021-03-17 12:34:52] 检查更新...                                      
INFO[2021-03-17 12:34:52] 发现新版本:v1.0.1                                 
INFO[2021-03-17 12:34:52] 请至'https://github.com/Xhofe/alist/releases/tag/v1.0.1'获取更新. 
INFO[2021-03-17 12:34:52] 读取配置文件...                                    
INFO[2021-03-17 12:34:52] 初始化client...                                 
INFO[2021-03-17 12:34:52] 初始化阿里云盘...                                   
INFO[2021-03-17 12:34:52] 刷新所有token...                                 
INFO[2021-03-17 12:34:52] 初始化数据库...                                    
INFO[2021-03-17 12:34:52] 初始化定时任务:刷新token                              
INFO[2021-03-17 12:34:52] 初始化路由...                                     
INFO[2021-03-17 12:34:52] Starting server @ 0.0.0.0:5244 
打开网站一直刷新中

**Comment by Xhofe** [comment]
刚开始忘记改版本号了，因为支持了多盘所以更新之后需要改一点配置文件

**Comment by szsyzx** [comment]
老大新版本配置文件有例子吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 中午1:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xhofe/alist-web] 为什么前后端都下载了1.0.1还是现实需要更新呢 (#9)




 
刚开始忘记改版本号了，因为支持了多盘所以更新之后需要改一点配置文件

**Comment by Xhofe** [comment]
已经包含在release中，或者可以在教程文章中查看
