### ISSUE TITLE
申请一个二级域名，如何把项目使用在二级域名下，https://qc.xx.cn/file/, 项目部署在https://qc.xx.cn/没有问题，但是多了file会出现问题

### ISSUE THREAD

**Issue by liuYanHarry** [Xhofe/alist-web#90]
正常情况下没有问题，如果放在二级路由下，就会出现问题

**Comment by liuYanHarry** [comment]
http://localhost:5173/file/， 路由后面添加了一个file/路径，数据请求也是加上了file/

**Comment by Lanfei** [comment]
配置 `site_url`：

https://alist.nn.ci/zh/config/configuration.html#site-url
